### PR TITLE
Adding a state flag to UserModule

### PR DESCRIPTION
**Pull request by mroda88**
UserModules have now a status that can indicates errors, etc. possible states can be extended. We need to decide what is checking on these state periodically.

### CODE REVIEW

**Comment by jcfreeman2** [comment]
I looked over the code; this branch is a good idea and I like how various guarantees in the code were made explicit (e.g., having UserModule::State() declared `const noexcept`). However, putting on my style-guide hat I have a couple questions/comments about the code itself:

-In general, a class's member data should only be private (Section 4.8 of the style guide). UserModule::fState is currently protected; can we make this private and then have a protected setter function? 

-For the UserModuleState enum: not that I feel super-emotional about this, but in Section 6.13 guide the suggestion is that an int be used for an integer type unless there's a good reason.

**Comment by mroda88** [comment]
Hi John, thanks for your comments. 
About the protect member, I'm absolutely ok with your suggestion. My solution was just cheap in terms of code to be written. I'll update as you suggests.

About the integer. Normally here I would have used a simple enum, not an integer. But I decided to make it a struct for two reasons:
1) it's more elegant to extend it with a "to_string" method that is more human understandable. (possible future upgrade)
2) the extension to a full class made me capable to specify the underlying integer type without letting the compiler make the decision. In this way the result of this query can be fed directly to a socket without issues. 

General comment that maybe I should have put at the top. 
This feature is supposed to be the be useful for one of the requirements on the Modules from the CCM: they have to be able to be ping-able. At the moment we don't have a CCM so this is just a draft that could grow into a proper nice feature. I would like people to start thinking what is the possible states we might want here.

**Comment by jcfreeman2** [comment]
Great. And the "result of this query can be fed directly to a socket without issues" absolutely qualifies as a good reason to go with `int16_t` instead of plain old `int`.

**Comment by eflumerf** [comment]
This pull request will not be included at this time.

**Pull request closed without merging**
